# Generated by Django 5.1.3 on 2024-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatures',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
