# Generated by Django 5.1.3 on 2024-11-22 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att2app', '0002_temperatures_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
